kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mongodb-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 27017
        hostPort: 27017
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker