apiVersion: v1 
kind: Service
metadata:
  name: mongodb-express-service
spec:
  type: LoadBalancer
  selector:
    app: mongodb-express
  
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30001